services:
  db:
    image: postgres:16-alpine
    container_name: user-authenticate-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-networks
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-networks

volumes:
  postgres_data:

networks:
  app-networks:
    driver: bridge
